config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'comments/index'
  end
  namespace :admin do
    get 'reviews/index'
    get 'reviews/show'
  end

  #---------------------------------------------------------------------------------------
  # public routes

  # guest_sign_in
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  # URL：/users/sign_in
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  scope module: :public do

    root to: 'homes#top'
    get 'search', to: 'homes#search', as: 'search'
    get 'users/mypage', to: 'users#show', as: 'mypage'
    get 'users/information/edit', to: 'users#edit', as: 'edit_information'
    patch 'users/information', to: 'users#update', as: 'update_information'
    get 'users/unsubscribe', to: 'users#unsubscribe', as: 'unsubscribe'
    patch 'users/withdraw', to: 'users#withdraw', as: 'withdraw'
    get 'mystores/:id/closing_confirm', to: 'mystores#closing_confirm', as: 'closing_confirm'
    patch 'mystores/:id/close', to: 'mystores#close', as: 'close'
    delete 'mystores/:mystore_id/mymenus/destroy_all', to: 'mymenus#destroy_all', as: 'destroy_all_mymenus'
    get 'reviews/history', to: 'reviews#history', as: 'store_review_history'

    resources :stores, only: %i(show) do
      resources :menus, only: %i(index)
      resources :reviews, only: %i(index new create show)
    end

    resources :mystores, only: %i(index new create show edit update) do
      resources :mymenus, only: %i(index create edit update destroy)
    end

    resources :reviews, only: %i() do
      resources :comments, only: %i(create)
      resource :favorites, only: %i(create destroy)
    end

  end

  #---------------------------------------------------------------------------------------
  # admin routes

  # URL：/admin/sign_in
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do

    root to: 'homes#top'

    resources :stores, only: %i(show edit update)

    resources :users, only: %i(index show edit update)

    resources :store_genres, only: %i(index create edit update)

    resources :reviews, only: %i(index show destroy) do
      resources :comments, only: %i(index)
    end

    resources :comments, only: %i(destroy)

  end

end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController

  before_action :identify_review, only: [:show, :destroy]

  def index
    # indexページの表示画面を判別
    if params[:user_id]
      @user = User.find(params[:user_id])
      all_review = @user.reviews
      # index画面(admin)のflag
      @index_screen_flag = 1

    elsif params[:store_id]
      @store = Store.find(params[:store_id])
      all_review = @store.reviews
      # index画面(admin)のflag
      @index_screen_flag = 2

    else
      all_review = Review.all
      # index画面(admin)のflag
      @index_screen_flag = 0
    end

    @reviews = all_review.page(params[:page]).per(10)

    if @index_screen_flag == 1 || @index_screen_flag == 2
      # ページごとのNo加算値の決定
      # params[:page] → 現在表示しているページ(※1ページ目はnil)
      # if params[:page]
      # params[:page]の中が数値 → trueとして評価
      # params[:page]の中がnil  → falseとして評価
      # page = params[:page]&.to_i
      # (params[:page].to_i - 1)
      # true(2ページ目以降) → 先頭の数値が、page - 1 × 10 + 1 (+ 1は後で加算)
      if params[:page]
        @number = (params[:page].to_i - 1) * 10
      else
        @number = 0
      end
    end
    
  end

  def show
  end

  def destroy
    if @review
      @review.destroy
    end
    redirect_to admin_reviews_path
  end

  private

  def identify_review
    @review = Review.find(params[:id])
  end

end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/views/admin/reviews/index.html.erb
<% if @index_screen_flag == 0 %>
  <div class = "admin_review_index_1 px-4">

    <h5 class = "admin_review_index_title">全ユーザーの口コミ投稿履歴</h5>

    <div class = "admin_review_index_table">
      <table class = "table table-borderless mb-4">
        <thead>
          <tr>
            <th class = "th1">口コミNo</th>
            <th class = "th2">投稿日時</th>
            <th class = "th3">投稿者</th>
            <th class = "th4">投稿店舗</th>
            <th class = "th5">投稿タイトル</th>
            <th class = "th6">点数</th>
          </tr>
        </thead>

        <% @reviews.each do |review| %>
          <tbody>
            <tr>
              <td class = "td1"><%= review.id %></td>
              <td class = "td2">
                <%= link_to review.created_at.strftime("%Y/%-m/%-d %H:%M:%S"), admin_review_path(review.id) %>
              </td>
              <td class = "td3">
                <%= link_to review.user.name, admin_reviews_path(user_id: review.user_id) %>
              </td>
              <td class = "td4">
                <%= link_to review.store.name, admin_reviews_path(store_id: review.store_id) %>
              </td>
              <td class = "td5"><%= review.title %></td>
              <td class = "td6"><%= review.score %>点</td>
            </tr>
          </tbody>
        <% end %>
      </table>

      <div>
        <%= paginate @reviews %>
      </div>

    </div>
  </div>

<% elsif @index_screen_flag == 1 %>
  <div class = "admin_review_index_2 px-4">

    <h5 class = "admin_review_index_title"><%= @user.name %>さんの口コミ投稿履歴</h5>

    <div class = "admin_review_index_table">
      <table class = "table table-borderless mb-4">
        <thead>
          <tr>
            <th class = "th1">No</th>
            <th class = "th2">投稿日時</th>
            <th class = "th4">投稿店舗</th>
            <th class = "th5">投稿タイトル</th>
            <th class = "th6">点数</th>
          </tr>
        </thead>

        <% @reviews.each_with_index do |review,i| %>
          <tbody>
            <tr>
              <td class = "td1"><%= i + 1 + @number %></td>
              <td class = "td2">
                <%= link_to review.created_at.strftime("%Y/%-m/%-d %H:%M:%S"), admin_review_path(review.id) %>
              </td>
              <td class = "td4">
                <%= link_to review.store.name, admin_reviews_path(store_id: review.store_id) %>
              </td>
              <td class = "td5"><%= review.title %></td>
              <td class = "td6"><%= review.score %>点</td>
            </tr>
          </tbody>
        <% end %>
      </table>

      <div>
        <%= link_to '＜　口コミ一覧に戻る', admin_reviews_path %>
      </div>

      <div>
        <%= paginate @reviews %>
      </div>

    </div>
  </div>

<% else %>
  <div class = "admin_review_index_3 px-4">

    <h5 class = "admin_review_index_title"><%= @store.name %>の口コミ投稿履歴</h5>

    <div class = "admin_review_index_table">
      <table class = "table table-borderless mb-4">
        <thead>
          <tr>
            <th class = "th1">No</th>
            <th class = "th2">投稿日時</th>
            <th class = "th3">投稿者</th>
            <th class = "th5">投稿タイトル</th>
            <th class = "th6">点数</th>
          </tr>
        </thead>

        <% @reviews.each_with_index do |review,i| %>
          <tbody>
            <tr>
              <td class = "td1"><%= i + 1 + @number %></td>
              <td class = "td2">
                <%= link_to review.created_at.strftime("%Y/%-m/%-d %H:%M:%S"), admin_review_path(review.id) %>
              </td>
              <td class = "td3">
                <%= link_to review.user.name, admin_reviews_path(user_id: review.user_id) %>
              </td>
              <td class = "td5"><%= review.title %></td>
              <td class = "td6"><%= review.score %>点</td>
            </tr>
          </tbody>
        <% end %>
      </table>

      <div>
        <%= link_to '＜　口コミ一覧に戻る', admin_reviews_path %>
      </div>

      <div>
        <%= paginate @reviews %>
      </div>

    </div>
  </div>

<% end %>

app/views/admin/reviews/show.html.erb
<div class = "admin_review_show px-4">

  <h5>口コミ詳細</h5>

  <div class = "row">

    <div class = "admin_review_show_review_contents col-8">

      <div class = "admin_review_show_item mb-4">
        <div class = "admin_review_show_store_title">投稿日時</div>
        <div class = "admin_review_show_store_content"><%= @review.created_at.strftime("%Y/%-m/%-d %H:%M:%S") %></div>
      </div>

      <div class = "admin_review_show_item mb-4">
        <div class = "admin_review_show_store_title">投稿者</div>
        <div class = "admin_review_show_store_content"><%= @review.name %></div>
      </div>

      <div class = "admin_review_show_item mb-4">
        <div class = "admin_review_show_store_title">投稿店舗</div>
        <div class = "admin_review_show_store_content"><%= @review.store.name %></div>
      </div>

      <div class = "admin_review_show_item mb-4">
        <div class = "admin_review_show_store_title">タイトル</div>
        <div class = "admin_review_show_store_content"><%= @review.title %></div>
      </div>

      <div class = "admin_review_show_item mb-4">
        <div class = "admin_review_show_store_title">内容</div>
        <div class = "admin_review_show_store_content"><%= @review.content %></div>
      </div>

      <div class = "admin_review_show_item mb-4">
        <div class = "admin_review_show_store_title">点数</div>
        <div class = "admin_review_show_store_score_bar">
          <div>
            <dd>
              <span style = "width: <%= @review.score.to_i %>%">
                <%= @review.score.to_i %>点
              </span>
            </dd>
          </div>
        </div>
      </div>
    </div>

    <div class = "col-4">

      <div class = "admin_review_show_image">
        <div class = "admin_store_show_image_title mb-2">投稿画像</div>
        <div><%= image_tag @review.get_review_image("300x300!") %></div>
      </div>
    </div>
  </div>

  <div class = "admin_review_show_button_group mt-5 mb-4">

    <%= link_to admin_reviews_path, class: "btn btn-success admin_review_show_return_button" do %>
      口コミ一覧に戻る
    <% end %>

    <%= link_to admin_review_path(@review.id), method: :delete, class: "btn btn-danger admin_review_show_destroy_button", data: { confirm: '本当に削除しますか？' } do %>
      削除する(不適切投稿)
    <% end %>

    <%= link_to admin_review_comments_path(@review.id), class: "btn admin_review_show_comment_button", style: "color: white; background-color: #FFAD90" do %>
      コメント一覧
    <% end %>

  </div>
</div>