config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'comments/index'
  end
  namespace :admin do
    get 'reviews/index'
    get 'reviews/show'
  end

  #---------------------------------------------------------------------------------------
  # public routes

  # guest_sign_in
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  # URL：/users/sign_in
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  scope module: :public do

    root to: 'homes#top'
    get 'search', to: 'homes#search', as: 'search'
    get 'users/mypage', to: 'users#show', as: 'mypage'
    get 'users/information/edit', to: 'users#edit', as: 'edit_information'
    patch 'users/information', to: 'users#update', as: 'update_information'
    get 'users/unsubscribe', to: 'users#unsubscribe', as: 'unsubscribe'
    patch 'users/withdraw', to: 'users#withdraw', as: 'withdraw'
    get 'mystores/:id/closing_confirm', to: 'mystores#closing_confirm', as: 'closing_confirm'
    patch 'mystores/:id/close', to: 'mystores#close', as: 'close'
    delete 'mystores/:mystore_id/mymenus/destroy_all', to: 'mymenus#destroy_all', as: 'destroy_all_mymenus'
    get 'reviews/history', to: 'reviews#history', as: 'store_review_history'

    resources :stores, only: %i(show) do
      resources :menus, only: %i(index)
      resources :reviews, only: %i(index new create show)
    end

    resources :mystores, only: %i(index new create show edit update) do
      resources :mymenus, only: %i(index create edit update destroy)
    end

    resources :reviews, only: %i() do
      resources :comments, only: %i(create)
      resource :favorites, only: %i(create destroy)
    end

  end

  #---------------------------------------------------------------------------------------
  # admin routes

  # URL：/admin/sign_in
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do

    root to: 'homes#top'

    resources :stores, only: %i(show edit update)

    resources :users, only: %i(index show edit update)

    resources :store_genres, only: %i(index create edit update)

    resources :reviews, only: %i(index show destroy) do
      resources :comments, only: %i(index)
    end

    resources :comments, only: %i(destroy)

  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :stores, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def self.guest
    find_or_create_by!(email: 'guest@example.com', name: 'guest', name_kana: 'guest', nickname: 'guest', postal_code: '9999999', address: 'xxxxxx', telephone_number: '9999999999', sex: 0) do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end

  validates :name, presence: true
  validates :name_kana, presence: true
  validates :nickname, presence: true
  validates :postal_code, presence: true, format: { with: /\A\d{7}\z/ } # 7桁の半角数字
  validates :sex, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true, format: { with: /\A\d{10,11}\z/ } # 半角数字ハイフンなしで10桁or11桁

  enum sex: { man: 0, woman: 1 }

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_action :authenticate_admin!
  before_action :identify_user, only: [:show, :edit, :update]

  def index
    @users = User.page(params[:page]).per(10)
  end

  def show
  end

  def edit
  end

  def update
    # user情報の更新可否
    if @user.update(user_params)
      redirect_to admin_user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :name_kana, :nickname, :postal_code, :address, :sex, :telephone_number, :email, :is_deleted)
  end

  def identify_user
    @user = User.find(params[:id])
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class = "admin_user_edit_form px-4">

  <h5><%= @user.name %>さんの会員情報編集&emsp;&ensp;<span class = "cautionary_note">全項目入力必須</span></h5>

  <div class = "admin_user_edit_id mb-4">
    <div class = "admin_user_edit_id_title">会員ID</div>
    <div class = "admin_user_edit_id_content"><%= @user.id %></div>
  </div>

  <%= form_with model: @user, url: admin_user_path(@user.id) do |f| %>

    <div class = "mb-4">
      <div class = "field">
        <%= f.label :name, "名前：", class: "admin_user_edit_label" %>
        <div class = "admin_user_edit_text_field">
          <%= f.text_field :name, placeholder: "名前を入力してください", class: "form-control" %>
        </div>
      </div>
      <div class = "mt-2">
        <!-- name_error -->
        <%= render "public/shared/error_messages", resource: @user, column: :name %>
      </div>
    </div>

    <div class = "mb-4">
      <div class = "field">
        <%= f.label :name_kana, "名前（カナ）：", class: "admin_user_edit_label" %>
        <div class = "admin_user_edit_text_field">
          <%= f.text_field :name_kana, placeholder: "名前（カナ）を入力してください", class: "form-control" %>
        </div>
      </div>
      <div class = "mt-2">
        <!-- name_kana_error -->
        <%= render "public/shared/error_messages", resource: @user, column: :name_kana %>
      </div>
    </div>

    <div class = "mb-4">
      <div class = "field">
        <%= f.label :nickname, "ニックネーム：", class: "admin_user_edit_label" %>
        <div class = "admin_user_edit_text_field">
          <%= f.text_field :nickname, placeholder: "ニックネームを入力してください", class: "form-control" %>
        </div>
      </div>
      <div class = "mt-2">
        <!-- nickname_error -->
        <%= render "public/shared/error_messages", resource: @user, column: :nickname %>
      </div>
    </div>

    <div class = "mb-4">
      <div class = "field">
        <%= f.label :sex, "性別：", class: "admin_user_edit_label" %>
        <div class = "admin_user_edit_radiobutton_field">
          <%= f.collection_radio_buttons :sex, User.sexes_i18n, :first, :last do |b| %>
            <%= b.label(class: "mr-5") { b.radio_button(class: "mr-2") + b.text } %>
          <% end %>
        </div>
      </div>
      <div class = "mt-2">
        <!-- sex_error -->
        <%= render "public/shared/error_messages", resource: @user, column: :sex %>
      </div>
    </div>

    <div class = "mb-4">
      <div class = "field">
        <%= f.label :postal_code, "郵便番号：", class: "admin_user_edit_label" %>
        <div class = "admin_user_edit_text_field">
          <%= f.text_field :postal_code, placeholder: "郵便番号を入力してください", class: "form-control" %>
        </div>
      </div>
      <div class = "mt-2">
        <!-- postal_code_error -->
        <%= render "public/shared/error_messages", resource: @user, column: :postal_code %>
      </div>
    </div>

    <div class = "mb-4">
      <div class = "field">
        <%= f.label :address, "住所：", class: "admin_user_edit_label" %>
        <div class = "admin_user_edit_text_field">
          <%= f.text_field :address, placeholder: "住所を入力してください", class: "form-control" %>
        </div>
      </div>
      <div class = "mt-2">
        <!-- address_error -->
        <%= render "public/shared/error_messages", resource: @user, column: :address %>
      </div>
    </div>

    <div class = "mb-4">
      <div class = "field">
        <%= f.label :telephone_number, "電話番号：", class: "admin_user_edit_label" %>
        <div class = "admin_user_edit_text_field">
          <%= f.text_field :telephone_number, placeholder: "電話番号を入力してください", class: "form-control" %>
        </div>
      </div>
      <div class = "mt-2">
        <!-- telephone_number_error -->
        <%= render "public/shared/error_messages", resource: @user, column: :telephone_number %>
      </div>
    </div>

    <div class = "mb-4">
      <div class = "field">
        <%= f.label :email, "メールアドレス：", class: "admin_user_edit_label" %>
        <div class = "admin_user_edit_email_field">
          <%= f.email_field :email, autofocus: true, autocomplete: "email", autocomplete: "email", placeholder: "メールアドレスを入力してください", class: "form-control" %>
        </div>
      </div>
      <div class = "mt-2">
        <!-- email_error -->
        <%= render "public/shared/error_messages", resource: @user, column: :email %>
      </div>
    </div>

    <div class = "mb-5">
      <div class = "field">
        <%= f.label :is_closed, "開店ステータス：", class: "admin_user_edit_label" %>
        <div class = "admin_user_edit_radiobutton_field">

          <% if @user.is_deleted == true %>
            <%= f.radio_button :is_deleted, :false %>
            <%= f.label :is_deleted, "有効", style: "margin-left: 4px; margin-bottom: 0px" %>
            <%= f.radio_button :is_deleted, :true, checked: "checked", style: "margin-left: 48px" %>
            <%= f.label :is_deleted, "退会", style: "margin-left: 4px; margin-bottom: 0px" %>

          <% else %>
            <%= f.radio_button :is_deleted, :false, checked: "checked" %>
            <%= f.label :is_deleted, "有効", style: "margin-left: 4px; margin-bottom: 0px" %>
            <%= f.radio_button :is_deleted, :true, style: "margin-left: 48px" %>
            <%= f.label :is_deleted, "退会", style: "margin-left: 4px; margin-bottom: 0px" %>

          <% end %>

        </div>
      </div>
    </div>

    <div class = "actions mb-4">
      <%= f.submit '変更を保存', class: "btn btn-success admin_user_update_button", data: { confirm: '本当に変更しますか？' } %>
    </div>

  <% end %>

</div>

app/views/admin/users/index.html.erb
<div class = "admin_user_index px-4">

  <h5>会員一覧</h5>

  <div class = "admin_user_index_view">
    <table class = "table table-borderless mb-4">
      <thead>
        <tr>
          <th class = "th1">会員ID</th>
          <th class = "th2">氏名</th>
          <th class = "th3">メールアドレス</th>
          <th class = "th4">会員ステータス</th>
        </tr>
      </thead>

      <% @users.each do |user| %>
        <tbody>
          <tr>
            <td class = "td1"><%= user.id %></td>
            <td class = "td2"><%= link_to user.name, admin_user_path(user.id) %></td>
            <td class = "td3"><%= user.email %></td>
            <% if user.is_deleted == true %>
              <td class = "td4" style = "color: red">退会</td>
            <% else %>
              <td class = "td4" style = "color: green">有効</td>
            <% end %>
          </tr>
        </tbody>
      <% end %>
    </table>

    <div>
      <%= paginate @users %>
    </div>

  </div>
</div>

app/views/admin/users/show.html.erb
<div class = "admin_user_show px-4">

  <h5><%= @user.name %>さんの会員詳細</h5>

  <div class = "admin_user_show_info mb-4">
    <div class = "admin_store_show_info_title">会員ID</div>
    <div class = "admin_store_show_info_content"><%= @user.id %></div>
  </div>

  <div class = "admin_user_show_info mb-4">
    <div class = "admin_store_show_info_title">名前</div>
    <div class = "admin_store_show_info_content"><%= @user.name %></div>
  </div>

  <div class = "admin_user_show_info mb-4">
    <div class = "admin_store_show_info_title">名前（カナ）</div>
    <div class = "admin_store_show_info_content"><%= @user.name_kana %></div>
  </div>

  <div class = "admin_user_show_info mb-4">
    <div class = "admin_store_show_info_title">ニックネーム</div>
    <div class = "admin_store_show_info_content"><%= @user.nickname %></div>
  </div>

  <div class = "admin_user_show_info mb-4">
    <div class = "admin_store_show_info_title">性別</div>
    <div class = "admin_store_show_info_content"><%= @user.sex_i18n %></div>
  </div>

  <div class = "admin_user_show_info mb-4">
    <div class = "admin_store_show_info_title">郵便番号</div>
    <div class = "admin_store_show_info_content">〒<%= @user.postal_code %></div>
  </div>

  <div class = "admin_user_show_info mb-4">
    <div class = "admin_store_show_info_title">住所</div>
    <div class = "admin_store_show_info_content"><%= @user.address %></div>
  </div>

  <div class = "admin_user_show_info mb-4">
    <div class = "admin_store_show_info_title">電話番号</div>
    <div class = "admin_store_show_info_content"><%= @user.telephone_number %></div>
  </div>

  <div class = "admin_user_show_info mb-4">
    <div class = "admin_store_show_info_title">メールアドレス</div>
    <div class = "admin_store_show_info_content"><%= @user.email %></div>
  </div>

  <div class = "admin_user_show_info mb-5">
    <div class = "admin_store_show_info_title">会員ステータス</div>
    <% if @user.is_deleted == true %>
      <div class = "admin_store_show_info_content" style = "color: red">退会</div>
    <% else %>
      <div class = "admin_store_show_info_content" style = "color: green">有効</div>
    <% end %>
  </div>

  <div class = "admin_user_show_button_group mb-4">

    <%= link_to edit_admin_user_path(@user.id), class: "btn btn-success admin_user_edit_button" do %>
      編集する
    <% end %>

    <%= link_to admin_root_path(user_id: @user.id), class: "btn btn-primary admin_user_store_index_button" do %>
      店舗登録履歴を見る
    <% end %>

    <%= link_to admin_reviews_path(user_id: @user.id), class: "btn admin_user_review_index_button", style: "color: white; background-color: #FFAD90" do %>
      口コミ投稿履歴を見る
    <% end %>

  </div>

</div>