config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'comments/index'
  end
  namespace :admin do
    get 'reviews/index'
    get 'reviews/show'
  end

  #---------------------------------------------------------------------------------------
  # public routes

  # guest_sign_in
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  # URL：/users/sign_in
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  scope module: :public do

    root to: 'homes#top'
    get 'search', to: 'homes#search', as: 'search'
    get 'users/mypage', to: 'users#show', as: 'mypage'
    get 'users/information/edit', to: 'users#edit', as: 'edit_information'
    patch 'users/information', to: 'users#update', as: 'update_information'
    get 'users/unsubscribe', to: 'users#unsubscribe', as: 'unsubscribe'
    patch 'users/withdraw', to: 'users#withdraw', as: 'withdraw'
    get 'mystores/:id/closing_confirm', to: 'mystores#closing_confirm', as: 'closing_confirm'
    patch 'mystores/:id/close', to: 'mystores#close', as: 'close'
    delete 'mystores/:mystore_id/mymenus/destroy_all', to: 'mymenus#destroy_all', as: 'destroy_all_mymenus'
    get 'reviews/history', to: 'reviews#history', as: 'store_review_history'

    resources :stores, only: %i(show) do
      resources :menus, only: %i(index)
      resources :reviews, only: %i(index new create show)
    end

    resources :mystores, only: %i(index new create show edit update) do
      resources :mymenus, only: %i(index create edit update destroy)
    end

    resources :reviews, only: %i() do
      resources :comments, only: %i(create)
      resource :favorites, only: %i(create destroy)
    end

  end

  #---------------------------------------------------------------------------------------
  # admin routes

  # URL：/admin/sign_in
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do

    root to: 'homes#top'

    resources :stores, only: %i(show edit update)

    resources :users, only: %i(index show edit update)

    resources :store_genres, only: %i(index create edit update)

    resources :reviews, only: %i(index show destroy) do
      resources :comments, only: %i(index)
    end

    resources :comments, only: %i(destroy)

  end

end

app/models/store_genre.rb
class StoreGenre < ApplicationRecord

  has_many :stores

  validates :name, presence: true, uniqueness: true

end

app/controllers/admin/store_genres_controller.rb
class Admin::StoreGenresController < ApplicationController

  before_action :authenticate_admin!
  before_action :identify_genre, only: [:edit, :update]

  def index
    @store_genre = StoreGenre.new
    @store_genres = StoreGenre.page(params[:page]).per(10)
  end

  def create
    @store_genre = StoreGenre.new(store_genre_params)
    # 店舗ジャンルの保存可否
    if @store_genre.save
      redirect_to admin_store_genres_path
    else
      @store_genres = StoreGenre.page(params[:page]).per(10)
      render :index
    end
  end

  def edit
  end

  def update
    # 店舗ジャンルの更新可否
    if @store_genre.update(store_genre_params)
      redirect_to admin_store_genres_path
    else
      render :edit
    end
  end

  private

  def store_genre_params
    params.require(:store_genre).permit(:name)
  end

  def identify_genre
    @store_genre = StoreGenre.find(params[:id])
  end

end

app/helpers/admin/store_genres_helper.rb
module Admin::StoreGenresHelper
end

app/views/admin/store_genres/edit.html.erb
<div class = "admin_store_genre_edit px-4">

  <h5>ジャンル編集</h5>

  <div class = "admin_store_genre_edit_form">

    <%= form_with model: @store_genre, url: admin_store_genre_path(@store_genre.id) do |f| %>

      <div class = "mb-4">
        <div class = "field">
          <div class = "admin_store_genre_edit_label">
            <%= f.label :name, "ジャンル名：", class: "mb-0" %>
            &emsp;&ensp;
            <span class = "cautionary_note">必須</span>
          </div>
          <div class = "admin_store_genre_edit_text_field">
            <%= f.text_field :name, placeholder: "ジャンル名を入力してください", class: "form-control" %>
          </div>
          <div class = "actions">
            <%= f.submit "変更を保存", class: "btn btn-success admin_store_genre_update_button" %>
          </div>
        </div>
        <div class = "mt-2">
          <!-- name_error -->
          <%= render 'layouts/error_message', model: @store_genre, column: :name %>
        </div>
      </div>

    <% end %>
  </div>
</div>

app/views/admin/store_genres/index.html.erb
<div class = "admin_store_genre_new_and_index px-4">

  <h5>ジャンル登録/一覧</h5>

  <div class = "admin_store_genre_new_form">

    <%= form_with model: @store_genre, url: admin_store_genres_path do |f| %>

      <div class = "mb-5">
        <div class = "field">
          <div class = "admin_store_genre_new_label">
            <%= f.label :name, "ジャンル名：", class: "mb-0" %>
            &emsp;&ensp;
            <span class = "cautionary_note">必須</span>
          </div>
          <div class = "admin_store_genre_new_text_field">
            <%= f.text_field :name, placeholder: "ジャンル名を入力してください", class: "form-control" %>
          </div>
          <div class = "actions">
            <%= f.submit "新規登録", class: "btn btn-success admin_store_genre_create_button" %>
          </div>
        </div>
        <div class = "mt-2">
          <!-- name_error -->
          <%= render 'layouts/error_message', model: @store_genre, column: :name %>
        </div>
      </div>

    <% end %>

  </div>

  <table class = "table table-borderless">
    <thead>
      <tr>
        <th class = "th1">ジャンル</th>
        <th class = "th2"></th>
      </tr>
    </thead>

    <% @store_genres.each do |store_genre| %>
      <tboby>
        <tr>
          <td class = "td1"><%= store_genre.name %></td>
          <td class = "td2">
            <div class = "admin_store_genre_button_group">
              <%= link_to edit_admin_store_genre_path(store_genre.id), class: "btn btn-success admin_store_genre_index_edit_button" do %>
                編集する
              <% end %>
            </div>
          </td>
        </tr>
      </tboby>
    <% end %>

  </table>

  <div>
    <%= paginate @store_genres %>
  </div>

</div>