config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'comments/index'
  end
  namespace :admin do
    get 'reviews/index'
    get 'reviews/show'
  end

  #---------------------------------------------------------------------------------------
  # public routes

  # guest_sign_in
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  # URL：/users/sign_in
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  scope module: :public do

    root to: 'homes#top'
    get 'search', to: 'homes#search', as: 'search'
    get 'users/mypage', to: 'users#show', as: 'mypage'
    get 'users/information/edit', to: 'users#edit', as: 'edit_information'
    patch 'users/information', to: 'users#update', as: 'update_information'
    get 'users/unsubscribe', to: 'users#unsubscribe', as: 'unsubscribe'
    patch 'users/withdraw', to: 'users#withdraw', as: 'withdraw'
    get 'mystores/:id/closing_confirm', to: 'mystores#closing_confirm', as: 'closing_confirm'
    patch 'mystores/:id/close', to: 'mystores#close', as: 'close'
    delete 'mystores/:mystore_id/mymenus/destroy_all', to: 'mymenus#destroy_all', as: 'destroy_all_mymenus'
    get 'reviews/history', to: 'reviews#history', as: 'store_review_history'

    resources :stores, only: %i(show) do
      resources :menus, only: %i(index)
      resources :reviews, only: %i(index new create show)
    end

    resources :mystores, only: %i(index new create show edit update) do
      resources :mymenus, only: %i(index create edit update destroy)
    end

    resources :reviews, only: %i() do
      resources :comments, only: %i(create)
      resource :favorites, only: %i(create destroy)
    end

  end

  #---------------------------------------------------------------------------------------
  # admin routes

  # URL：/admin/sign_in
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do

    root to: 'homes#top'

    resources :stores, only: %i(show edit update)

    resources :users, only: %i(index show edit update)

    resources :store_genres, only: %i(index create edit update)

    resources :reviews, only: %i(index show destroy) do
      resources :comments, only: %i(index)
    end

    resources :comments, only: %i(destroy)

  end

end

app/views/layouts/_error_message.html.erb
<!-- error message 用の部分テンプレート -->
<% if model.errors.include?(column) %>
  <% model.errors.full_messages_for(column).each do |message| %>
    <li class = "text-danger"><%= message %></li>
  <% end %>
<% end %>

app/views/layouts/_error_messages.html.erb
<!-- error message 用の部分テンプレート -->
<% if model.errors.include?(column) %>
  <% model.errors.full_messages_for(column).each do |message| %>
    <li><%= message %></li>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- FontAwesome -->
    <script src="https://kit.fontawesome.com/b68ddd792a.js" crossorigin="anonymous"></script>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>RAMAP</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <!-- 応急処置：width → 576px以下に対する処置 -->
  <body style = "min-width: 576px">
    <header>
      <nav class = "navbar navbar-expand-xl navbar-light px-5" style = "background-color: #e3f2fd">
        <div class = "container-fluid">
          <%= link_to root_path, class: "navbar-brand" do %>
            <%= image_tag 'ramap_logo.png', :size => '50x50' %>&ensp;<span class = "application_title">RAMAP</span>
          <% end %>

          <button class = "navbar-toggler" type = "button" data-toggle = "collapse" data-target = "#navbarNavDropdown" aria-controls = "navbarNavDropdown" aria-expanded = "false" aria-label = "Toggle navigation">
            <span class = "navbar-toggler-icon"></span>
          </button>

          <div class = "collapse navbar-collapse" id = "navbarNavDropdown">
            <ul class = "navbar-nav ml-auto">
              <% if admin_signed_in? %>
                <li class = "nav-item">
                  <%= link_to 'TOPページ', admin_root_path, class: "nav-link active" %>
                </li>
                <li class = "nav-item">
                  <%= link_to '会員一覧', admin_users_path, class: "nav-link active" %>
                </li>
                <li class = "nav-item">
                  <%= link_to 'ジャンル一覧', admin_store_genres_path, class: "nav-link active" %>
                </li>
                <li class = "nav-item">
                  <%= link_to '口コミ一覧', admin_reviews_path, class: "nav-link active" %>
                </li>
                <li class = "nav-item">
                  <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: "nav-link active" %>
                </li>

              <% elsif user_signed_in? %>
                <li class = "nav-item">
                  <%= link_to 'TOPページ', root_path, class: "nav-link active" %>
                </li>
                <li class = "nav-item">
                  <%= link_to 'マイページ', mypage_path, class: "nav-link active" %>
                </li>
                <li class = "nav-item">
                  <%= link_to '店舗情報（一覧）', mystores_path, class: "nav-link active" %>
                </li>
                <li class = "nav-item">
                  <%= link_to '口コミ投稿履歴', store_review_history_path, class: "nav-link active" %>
                </li>
                <li class = "nav-item">
                  <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "nav-link active" %>
                </li>

              <% else %>
                <li class = "nav-item">
                  <%= link_to 'TOPページ', root_path, class: "nav-link active" %>
                </li>
                <li class = "nav-item">
                  <%= link_to '会員登録', new_user_registration_path, class: "nav-link active" %>
                </li>
                <li class = "nav-item">
                  <%= link_to '会員ログイン',new_user_session_path, class: "nav-link active" %>
                </li>
                <li class = "nav-item">
                  <%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post, class: "nav-link active" %>
                </li>

              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main class = "mt-5">
      <%= yield %>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

  </body>
</html>